name: codiga (code quality)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codiga/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          codiga_api_token: ${{ secrets.CODIGA_API_TOKEN }}
          force_ref: 'none'
          min_quality_score: '90'
          max_defects_rate: '0.1'
          max_complex_functions_rate: '0.7'
          max_long_functions_rate: '0.7'
          max_timeout_sec: '60'
